spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://<HOST>:<PORT>/<DBNAME>?ssl-mode=REQUIRED}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver   # remove or correct any org.h2.Driver entry
  jpa:
    hibernate:
      ddl-auto: update        # <<-- changed for dev: update (creates/updates tables)
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  cors:
    # allow common local dev origins
    allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"