spring:
  datasource:
    # local dev uses in-memory H2 to make frontend work without external DB;
    # remove or override when you want to use Aiven (use env vars instead)
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  cors:
    # allow common local dev origins
    allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"